### ISSUE TITLE
can't set the list height manually

### ISSUE THREAD

**Issue by rnmhdn** [Coal0/Utilities#1]
in order to fix this, line 185:
self.listbox_widget["height"] = self.DEFAULT_LISTBOX_HEIGHT
should be removed.

**Comment by coal0** [comment]
I'll see to this and the other issue ASAP. I rewrote the whole file before having read your issues so this should be easier to manage now.

**Comment by coal0** [comment]
Issue was resolved [here](https://github.com/Coal0/Utilities/pull/3).
