### ISSUE TITLE
contains is better than startswith()

### ISSUE THREAD

**Issue by rnmhdn** [Coal0/Utilities#2]
I think in most autocompletion usages containing is much more important than beginning with or lcs so I think it's better you set the default to match_exact and you change line 203 to:
`if text in entry.strip():`
I also think it's better to add these lines in under line 186:
```
if len(text) < 3:
    return
```

**Comment by coal0** [comment]
Issue was resolved [here](https://github.com/Coal0/Utilities/pull/3).
