### ISSUE TITLE
Drop down prediction menu

### ISSUE THREAD

**Issue by kaizziz** [Coal0/Utilities#4]
Hello! First of all, thank you very much for this autocomplete menu widget, I really needed it.

The thing is, when I search for something in the entry box, the autocomplete displaces everything. Is there a way to avoid it? Also, when I successfully search for something, the autocomplete dropdown doesn't disappear, is there a way to make it go away?

Thanks in advance.

**Comment by coal0** [comment]
Terribly sorry not to get back to you on time. In case you or future readers still need help with this, shoot me an email.
